# Generated by Django 2.2.20 on 2021-04-25 01:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='start_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
