# Generated by Django 2.2.20 on 2021-04-25 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=50)),
                ('room_num', models.IntegerField(default=1)),
                ('floor_num', models.IntegerField(default=1)),
            ],
        ),
    ]
